version: '3.3'
services:
  db:
    image: postgres:11.8
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - /var/run/postgres/postgres.sock:/var/run/postgres/postgres.sock
      - db-volume:/var/lib/postgresql/data

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    image: backend-image
    container_name: backend
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/home/app

  frontend:
    build: ./frontend
    environment:
      CHOKIDAR_USEPOLLING: "true"
    image: frontend-image
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app

volumes:
  db-volume: