# Generated by Django 3.2.5 on 2021-07-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_game_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='npc',
            field=models.BooleanField(default=False),
        ),
    ]
